image: node:latest

before_script:
  - apt-get update && apt-get install --no-install-recommends yarn -y

variables:

  DOCKER_USERNAME: keematContainer
  DOCKER_PASSWORD: LaZCLWCmlxMSJojcCf+9YSRvZEsotSOz
  DOCKER_REPO: keematcontainer.azurecr.io/express_backend
  DOCKER_LOGIN_URL: keematcontainer.azurecr.io
#   HEROKU_ACCESS_TOKEN: ae775e38-1c25-4a9c-97c8-017e4a77027c
#   HEROKU_APP_NAME: qemat-staging

stages:
#   - compile
#   - test
  - build
#   - deploy

# compile:
#   stage: compile
#   script:
#     - mv .env .env.backup
#     - mv .test.env .env
#     - rm -rf node_modules
#     - rm -rf yarn.lock
#     - yarn cache clean
#     - yarn setup
#     - mv .env .test.env
#     - mv .env.backup .env

# test:
#   stage: test
#   script:
#     - mv .env .env.backup
#     - mv .test.env .env
#     - rm -rf node_modules
#     - rm -rf yarn.lock
#     - yarn cache clean
#     - yarn setup
#     - yarn start test
#     - mv .env .test.env
#     - mv .env.backup .env

build_image:
    stage: build
    image: docker:latest
    services:
      - docker:dind

    before_script:
      - mv .env .env.backup
      - mv .stage.env .env
      - docker login $DOCKER_LOGIN_URL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - apk update && apk add yarn
      - apk update && apk add nodejs
      - apk update && apk add npm
      - cp src/database/storageforseeding/main/price.json src/database/storageforseeding/price.json
      - cp src/database/storageforseeding/main/scatterplotstuff.json src/database/storageforseeding/scatterplotstuff.json
      - cp src/database/storageforseeding/main/vehiclemodels.json src/database/storageforseeding/vehiclemodels.json


    script:
      - rm -rf node_modules
      - rm -rf yarn.lock
      - yarn cache clean
      - yarn setup
      - npm install
      - yarn start build
      - docker build -t demo .
      - docker tag demo $DOCKER_REPO
      - docker push $DOCKER_REPO
      - echo "Docker image build succeeded and pushed to azure registry"


# deploy_stage:
#   stage: deploy
#   image: docker:latest
#   services:
#     - docker:dind

#   variables:
#     DOCKER_DRIVER: overlay

#   before_script:
#     - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#     - docker login -u _ -p $HEROKU_ACCESS_TOKEN registry.heroku.com

#   script:
#     - docker pull $DOCKER_REPO
#     - docker tag  $DOCKER_REPO registry.heroku.com/$HEROKU_APP_NAME/web
#     - docker push registry.heroku.com/$HEROKU_APP_NAME/web
#     - echo "Pulled from docker and then pushed to stagin registry heroku"
#     - apk add --update curl && rm -rf /var/cache/apk/*
#     - chmod +x ./release.sh
#     - ./release.sh $HEROKU_APP_NAME $HEROKU_ACCESS_TOKEN
#     - echo "Released to staging server on heroku"
#     - |-
#         curl -X PATCH https://qemat-staging.herokuapp.com/api/histogram/generateStats
#   only:
#     - dev
#   environment:
#     name: staging
