import { BatteryCharging } from './BatteryChargingDTO';
import { BatteryRanges } from './BatteryRanges';
import { DriveMapCalDTO } from './DriveMapCalDTO';
import { KeyValuePair } from './KeyValuePairDTO';
import { LastMonthStats } from './LastMonthStatsDTO';
import { Stats } from './StatsDTO';
import { VehicleDTO } from './VehicleDTO';

export interface Dashboard {
    name:  string;
    carVersion:  string;
    vin:  string;
    carType:  string;
    vehicleStartDate:  string;
    hoursDriving:  string;
    totalDistance:  string;
    odometer:  number;
    averageSpeed:  string;
    driveSafetyScore:  number;
    carModel:  string;
    modelYear: number;
    manufactorere:  string;
    chargePortType:  string;
    vehicleMarket:  string;
    exteriorColour:  string;
    trimBadging:  string;
    wheelType:  string;
    airSuspension:  string;
    ludicrousMode:  string;
    steeringWheel:  string;
    spoilerType:  string;
    carSpecialType:  string;
    hasLudicrousMode:  string;
    hasAirSuspension:  string;
    perfConfig:  string;
    roofColor:  string;
    thirdRowSeats:  string;
    timeZone:  string;
    optionsCodes: string[];
    codesT: KeyValuePair[];
    speedUnit: string;
    lastMonthStats: LastMonthStats[];
    last24HoursBatteryRanges: BatteryRanges[];
    last4WeeksBatteryRanges: BatteryRanges[];
    last24HoursBatteryCharging: BatteryCharging[];
    last24HoursStats: Stats[];
    last7DaysStats: Stats[];
    userVehicles: VehicleDTO[];
    driveMapCal: DriveMapCalDTO;
    badges: string[];
}
